spring.application.name=SPTTS
# server
server.port=8080

# db
spring.datasource.url=jdbc:postgresql://localhost:5432/sptts
spring.datasource.username=postgres
spring.datasource.password=PASSWORD
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver

# jwt
jwt.secret=QstzqwqHV2ZYB3EzmGZSXKqkm8d7nFfjeeGv3NUbl/sEha7sgfrg9Mu+MDBnf1HYkCZlJVZ/rL0tjgRNYrf/jw==
jwt.expiration=86400000

# swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
